# Backtest of **Intra-Day** Risk-Control Reweighting using Quantile Forecasts from a Bayesian Joint Quantile Time Series Model For Asset Returns

## Import packages

### Set up automatic reload of packages and modules that change

In [7]:
# register autoreload extension and thus register hooks 
# to reload modules automatically before entering the execution of code 
# typed at the IPython prompt.
%load_ext autoreload

# set autoreload mode to 2, which reloads all modules (except those excluded by %aimport)
# every time before executing the Python code typed (applies to all cells)
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Set up Longer tracebacks for debugging

In [8]:
#%xmode Verbose
%xmode Plain

Exception reporting mode: Plain

### Import libraries

In [9]:
# Standard library imports
import importlib  # Allows dynamic import of modules without having to restart the kernel
import json       # JSON encoder and decoder
import os         # Operating system interfaces
from pathlib import Path  # Object-oriented filesystem paths
import sys        # System-specific parameters and functions
import traceback # error handling

# API Libraries and Data Extraction
import yfinance as yf  # Yahoo Finance API for financial data extraction

# Data manipulation and analysis
import h5py                     # HDF5 file format for storing large datasets
from itertools import product   # For generating combinations of parameters
import numpy as np              # Numerical operations
import openpyxl as px           # Excel file reading and writing
import pandas as pd             # DataFrame and data analysis
from scipy.io import loadmat    # MATLAB file format for loading data

# Plotting and visualization
import matplotlib.colors as mcolors  # Color utilities for matplotlib for different line series colours
import matplotlib.dates as mdates    # Date formatting for matplotlib
import matplotlib.pyplot as plt      # Static plotting
import plotly.graph_objects as go     # Interactive plotting (core interface)
from IPython.display import display  # Display objects in Jupyter notebooks

# Interactive Plotting
from dash import Dash, Input, Output, dcc, html  # Dash web application components

# Grammar of graphics plotting (ggplot-style)
from plotnine import *                     # Main plotnine API for ggplot-style plotting
from plotnine.scales import scale_x_date   # For date scaling on x-axis in plotnine

# Warnings control
import warnings                             # Warning control
from plotnine.exceptions import PlotnineWarning  # Plotnine-specific warnings

### Import Custom Packages

In [10]:
# import custom function under ../src/stats_utils
# first, add the parent directory to sys.path
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

# Plotting

import  src.stats_utils.dash_timeseries_app as dta
from src.stats_utils.dash_timeseries_app import LevelDashApp, LevelAppConfig, GradientColourMap

# Statistics and performance calculation
import src.stats_utils.performance as pm
from src.stats_utils.returns import ReturnsCalculator, ReturnsConfig

## Import and clean the S&P Capital IQ (CIQ) data for SPX and SPY

### Import the CIQ data

In [11]:
# import the interday S&P 500 data from the csv file in the data directory
intraday_data_ciq = pd.read_excel("../data/input/spx_spy_CIQ_Pro_10_min_max.xlsx")

### Clean the CIQ Data

#### Change column names

In [12]:
# Rename the columns to time, val_wgt_ret_w_div, level, base_return, in that order
intraday_data_ciq_v1 = intraday_data_ciq.copy()
intraday_data_ciq_v1.columns = ['time', 'spx_level', 'spy_level']

#### Clean the date column

In [13]:
# convert time column to string first
intraday_data_ciq_v2 = intraday_data_ciq_v1.copy()
intraday_data_ciq_v2['time'] = intraday_data_ciq_v2['time'].astype(str)

# split the time column upon - (only applies to the misformatted dates)
# these dates are in yyyy-dd-mm hh:mm:ss format when should be mm/dd/yyyy hh:mm (US format)
# for each row that contains a '-' in the time string, move the yyyy so that it goes after
# the dd and mm but before the hh:mm
#regex = r'[\s-]+'
#sp500_intraday['time'] = sp500_intraday['time'].apply(lambda x:
#                                                        f"{x.split(regex)[1]}/{x.split(regex)[2]}/{x.split(regex)[0]} {x.split(' ')[1]}"
#                                                         if '-' in x else x)
intraday_data_ciq_v2['time'] = intraday_data_ciq_v2['time'].str.split(r'[\s\-/]+', expand=False)

# identify if the first part is greater than 12, then it's yyyy-dd-mm
intraday_data_ciq_v2['time'] = intraday_data_ciq_v2['time'].apply(lambda x: 
                                                         f"{x[2]}/{x[1]}/{x[0]} {x[3][:-3]}"
                                                         if int(x[0]) == 2025 else f"{x[0]}/{x[1]}/{x[2]} {x[3]}")

In [14]:
# Convert the time column to datetime format, 
# considering they are currently string format as dd/mm/yyyy hh:mm
intraday_data_ciq_v3 = intraday_data_ciq_v2.copy()
intraday_data_ciq_v3['time'] = pd.to_datetime(intraday_data_ciq_v3['time'], format='%m/%d/%Y %H:%M')
# sort in ascending order
intraday_data_ciq_v3 = intraday_data_ciq_v3.drop_duplicates().sort_values(by = 'time' ,ascending=True).reset_index().drop('index', axis=1)

#convert back to object
#intraday_data_ciq_v3['time_label'] = intraday_data_ciq_v3['time'].astype(object)

In [15]:
# inspect the clean date column
intraday_data_ciq_v3

                   time  spx_level  spy_level
0   2025-11-10 19:00:00        NaN        NaN
1   2025-11-28 09:30:00    6825.28     679.06
2   2025-11-28 09:40:00    6830.12     679.52
3   2025-11-28 09:50:00    6826.03     679.23
4   2025-11-28 10:00:00    6829.63     679.48
..                  ...        ...        ...
849 2025-12-26 15:50:00    6930.52     690.25
850 2025-12-26 16:00:00    6929.94     690.24
851 2025-12-26 16:10:00    6929.94        NaN
852 2025-12-26 16:15:00        NaN     690.31
853 2025-12-26 16:20:00    6929.94        NaN

[854 rows x 3 columns]

## Import and clean Yahoo Finance (YF) data for SPX, SPY and ES

### Import YF data

In [16]:
# Import 15 minute frequency data for SPX
spx_15_mn_yf = yf.download("^GSPC", interval="5m", period="60d")
# Import 15 minute frequency data for SPY
spy_15_min_yf = yf.download("SPY", interval="5m", period="60d")
# Import 15 minute frequency data for ES
es_15_min_yf = yf.download("ES=F", interval="5m", period="60d")

C:\Users\danie\AppData\Local\Temp\ipykernel_33184\2756754222.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
[*********************100%***********************]  1 of 1 completed
C:\Users\danie\AppData\Local\Temp\ipykernel_33184\2756754222.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
[*********************100%***********************]  1 of 1 completed
C:\Users\danie\AppData\Local\Temp\ipykernel_33184\2756754222.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
[*********************100%***********************]  1 of 1 completed

### Merge the Yahoo Finance Datasets

In [17]:
# Merge these 3 datasets' first columns (close) on their datetime index
intraday_data_yf = pd.merge(spx_15_mn_yf.iloc[:,0], spy_15_min_yf.iloc[:,0],  left_index=True, right_index=True, how='inner', suffixes=('_SPX', '_SPY'))
# Then merge with ES data
intraday_data_yf = pd.merge(intraday_data_yf, es_15_min_yf.iloc[:,0], left_index=True, right_index=True, how='inner')
# Change the datetime index to be a separate column
intraday_data_yf.reset_index(inplace=True)
intraday_data_yf

                      Datetime        Close
                                      ^GSPC         SPY     ES=F
0    2025-11-12 14:30:00+00:00  6861.459961  684.229980  6885.25
1    2025-11-12 14:35:00+00:00  6867.600098  684.804993  6891.25
2    2025-11-12 14:40:00+00:00  6861.540039  684.159973  6884.50
3    2025-11-12 14:45:00+00:00  6852.209961  683.320007  6876.00
4    2025-11-12 14:50:00+00:00  6855.220215  683.534973  6878.00
...                        ...          ...         ...      ...
3740 2026-01-23 20:35:00+00:00  6912.359863  688.929993  6943.50
3741 2026-01-23 20:40:00+00:00  6915.509766  689.219971  6946.25
3742 2026-01-23 20:45:00+00:00  6916.879883  689.400085  6948.00
3743 2026-01-23 20:50:00+00:00  6914.200195  689.075012  6944.75
3744 2026-01-23 20:55:00+00:00  6915.160156  689.179993  6945.50

[3745 rows x 4 columns]

### Clean The Yahoo Finance Data

#### Rename columns

In [18]:
# Change the column names to 'time', spx_level_yf, spy_level_yf, es_level_yf
intraday_data_yf.columns = ['time', 'spx_level_yf', 'spy_level_yf', 'es_level_yf']
intraday_data_yf

                          time  spx_level_yf  spy_level_yf  es_level_yf
0    2025-11-12 14:30:00+00:00   6861.459961    684.229980      6885.25
1    2025-11-12 14:35:00+00:00   6867.600098    684.804993      6891.25
2    2025-11-12 14:40:00+00:00   6861.540039    684.159973      6884.50
3    2025-11-12 14:45:00+00:00   6852.209961    683.320007      6876.00
4    2025-11-12 14:50:00+00:00   6855.220215    683.534973      6878.00
...                        ...           ...           ...          ...
3740 2026-01-23 20:35:00+00:00   6912.359863    688.929993      6943.50
3741 2026-01-23 20:40:00+00:00   6915.509766    689.219971      6946.25
3742 2026-01-23 20:45:00+00:00   6916.879883    689.400085      6948.00
3743 2026-01-23 20:50:00+00:00   6914.200195    689.075012      6944.75
3744 2026-01-23 20:55:00+00:00   6915.160156    689.179993      6945.50

[3745 rows x 4 columns]

#### Clean the time column

In [19]:
# Date/time is currently is object format as 2025-10-17 13:30:00+00:00
# but should be converted to datetime format as dd/mm/yyyy hh:mm without the +00:00
# must also convert to EST from UTC
intraday_data_yf_v2 = intraday_data_yf.copy()
intraday_data_yf_v2['time'] = pd.to_datetime(intraday_data_yf_v2['time']).dt.tz_convert('US/Eastern').dt.tz_localize(None)

# sort in ascending date order
intraday_data_yf_v2 = intraday_data_yf_v2.sort_values(by='time', ascending=True).reset_index().drop('index', axis=1)

intraday_data_yf_v2

                    time  spx_level_yf  spy_level_yf  es_level_yf
0    2025-11-12 09:30:00   6861.459961    684.229980      6885.25
1    2025-11-12 09:35:00   6867.600098    684.804993      6891.25
2    2025-11-12 09:40:00   6861.540039    684.159973      6884.50
3    2025-11-12 09:45:00   6852.209961    683.320007      6876.00
4    2025-11-12 09:50:00   6855.220215    683.534973      6878.00
...                  ...           ...           ...          ...
3740 2026-01-23 15:35:00   6912.359863    688.929993      6943.50
3741 2026-01-23 15:40:00   6915.509766    689.219971      6946.25
3742 2026-01-23 15:45:00   6916.879883    689.400085      6948.00
3743 2026-01-23 15:50:00   6914.200195    689.075012      6944.75
3744 2026-01-23 15:55:00   6915.160156    689.179993      6945.50

[3745 rows x 4 columns]

## Merge and manipulate datasets from different sources together

### Perform the merge

In [20]:
# Merge the intraday_data with intraday_data_ciq_v3 on the time column,
# keeping all rows from intraday_data_ciq_v3
intraday_data = pd.merge(intraday_data_yf_v2, intraday_data_ciq_v3, on='time', how='right')

# reorder the two spx columns to go first, then es, then the two spy columns
intraday_data = intraday_data[['time', 'spx_level', 'spx_level_yf', 'es_level_yf', 'spy_level', 'spy_level_yf']]

### Calculate returns

In [21]:
# drop empty rows
intraday_data_v2 = intraday_data.copy().dropna().reset_index().drop('index', axis=1)

#### Add log return and cumulative return columns

In [22]:
# run an instance of the ReturnsCalculator class from the returns.py module to compute log returns
calc = ReturnsCalculator(ReturnsConfig(return_kind="log", inplace=False))

# run the transform method of the ReturnsCalculator instance to compute the returns
intraday_data_v3 = calc.transform(intraday_data_v2)

#### Reorganise columns

In [23]:

# Create a dataframe of only the returns
# intraday_returns = intraday_data_v3.copy().drop(columns=[col for col in intraday_returns_df.columns if 'level' in col])

# reorder columns to have time first, then
    # all the columns with 'level' in their name, then
    # all the columns with 'period_return' in their name, 
    # then all the columns with 'total_return' in their name
intraday_data_v4 = intraday_data_v3.copy()
intraday_data_v4 = intraday_data_v4[['time'] + [col for col in intraday_data_v4.columns if 'level' in col] +
                                   [col for col in intraday_data_v4.columns if 'period_return' in col] +
                                   [col for col in intraday_data_v4.columns if 'total_return' in col]]
intraday_data_v4

,time,spx_level,spx_level_yf,es_level_yf,spy_level,spy_level_yf,spx_period_return,spx_period_return_yf,es_period_return_yf,spy_period_return,spy_period_return_yf,spx_total_return,spx_total_return_yf,es_total_return_yf,spy_total_return,spy_total_return_yf
0,2025-11-28 09:30:00,6825.28,6829.910156,6840.00,679.06,681.489990,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025-11-28 09:40:00,6830.12,6826.770020,6838.50,679.52,681.270020,0.000709,-0.000460,-0.000219,0.000677,-0.000323,0.000709,-0.000460,-0.000219,0.000677,-0.000323
2,2025-11-28 09:50:00,6826.03,6828.250000,6838.75,679.23,681.304993,-0.000599,0.000217,0.000037,-0.000427,0.000051,0.000110,-0.000243,-0.000183,0.000250,-0.000271
3,2025-11-28 10:00:00,6829.63,6826.049805,6838.25,679.48,681.229919,0.000527,-0.000322,-0.000073,0.000368,-0.000110,0.000637,-0.000565,-0.000256,0.000619,-0.000382
4,2025-11-28 10:10:00,6833.94,6831.149902,6842.50,679.99,681.630005,0.000631,0.000747,0.000621,0.000750,0.000587,0.001269,0.000182,0.000365,0.001370,0.000205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,2025-12-26 15:10:00,6929.26,6929.899902,6978.25,690.16,690.180115,-0.000068,0.000025,0.000036,0.000014,0.000044,0.015235,0.014640,0.020212,0.016346,0.012752
738,2025-12-26 15:20:00,6930.09,6930.140137,6978.50,690.20,690.200012,0.000120,0.000035,0.000036,0.000058,0.000029,0.015356,0.014675,0.020249,0.016405,0.012781
739,2025-12-26 15:30:00,6931.67,6930.509766,6978.75,690.38,690.250000,0.000228,0.000053,0.000036,0.000261,0.000072,0.015588,0.014729,0.020285,0.016670,0.012854
740,2025-12-26 15:40:00,6931.01,6932.500000,6981.25,690.31,690.450012,-0.000095,0.000287,0.000358,-0.000101,0.000290,0.015491,0.015021,0.020651,0.016567,0.013148
741,2025-12-26 15:50:00,6930.52,6928.459961,6977.75,690.25,690.070007,-0.000071,-0.000583,-0.000501,-0.000087,-0.000551,0.015419,0.014429,0.020139,0.016479,0.012590

#### Drop the returns calculated as overnight returns

In [24]:
# drop all the rows where time is 9:30, since the return value for that row is 
# actually the overnight return (market open)
# experienced over multiple hours, not over the 10-minute interval

intraday_data_v5 = intraday_data_v4[~((intraday_data_v4['time'].dt.hour == 9) & 
                                                        (intraday_data_v4['time'].dt.minute == 30))].reset_index().drop('index', axis=1)

## EDA of combined price / index level data

### Plot the S&P 500 index and instrument levels from different sources

#### Plot setup

In [25]:
# Specify the correct columns that we want to plot:
# all the columns that have 'level' in their name

level_cols = ["spx_level", "spx_level_yf", "es_level_yf"]

level_cols

['spx_level', 'spx_level_yf', 'es_level_yf']

In [26]:
# add a colour map
# start with light blue to purple gradient for the different level series
gen = GradientColourMap(level_cols, start="cyan", end="purple")
levels_colour_map = gen.run()          # or gen.run(); colour_map_values = gen.colour_map

#### Plot display

In [27]:
# enter those parameters into the dash app that creates the plot
cfg = LevelAppConfig(
    cols_of_interest=level_cols,
    reindex=False,
    colour_map=levels_colour_map,
    title="Comparison of Levels",
    figure_title="Levels over Selected Period",
    fig_height=800,
    port=8050,
)

# run the app (produce the plot)
dash_app = LevelDashApp(intraday_data_v5, cfg)
dash_app.run(debug=True)

### Plot the S&P 500 index and instrument returns from different sources

#### Plot setup

In [28]:
# Specify the correct columns that we want to plot:
# all the columns that have 'period_return' in their name

period_return_cols = [col for col in intraday_data_v5.columns if 'spx_period_return' in col]

period_return_cols

['spx_period_return', 'spx_period_return_yf']

In [29]:
# add a colour map
# start with light blue to purple gradient for the different level series
gen = GradientColourMap(period_return_cols, start="cyan", end="purple")
period_return_colour_map = gen.run()          # or gen.run(); colour_map_values = gen.colour_map

#### Plot display

In [30]:
# enter those parameters into the dash app that creates the plot
cfg = LevelAppConfig(
    cols_of_interest=period_return_cols,
    reindex=False,
    colour_map=period_return_colour_map,
    title="Comparison of Returns",
    figure_title="Returns over Selected Period",
    fig_height=800,
    port=8051,
)

# run the app (produce the plot)
dash_app = LevelDashApp(intraday_data_v5, cfg)
dash_app.run(debug=True)

### Plot the S&P 500 index and instrument returns from different sources

#### Plot setup

In [31]:
# Specify the correct columns that we want to plot:
# all the columns that have 'period_return' in their name

total_return_cols = [col for col in intraday_data_v5.columns if 'total_return' in col]

total_return_cols

['spx_total_return',
 'spx_total_return_yf',
 'es_total_return_yf',
 'spy_total_return',
 'spy_total_return_yf']

In [32]:
# add a colour map
# start with light blue to purple gradient for the different level series
gen = GradientColourMap(total_return_cols, start="cyan", end="purple")
total_return_colour_map = gen.run()          # or gen.run(); colour_map_values = gen.colour_map

#### Plot display

In [33]:
# enter those parameters into the dash app that creates the plot
cfg = LevelAppConfig(
    cols_of_interest=total_return_cols,
    reindex=False,
    colour_map=total_return_colour_map,
    title="Comparison of Total Returns",
    figure_title="Total Returns over Selected Period",
    fig_height=800,
    port=8052,
)

# run the app (produce the plot)
dash_app = LevelDashApp(intraday_data_v5, cfg)
dash_app.run(debug=True)

## Save Out to Excel File for Processing

In [34]:
# select only the spx level with the datetime time column
spx_excel_intraday = intraday_data_v5[['time','spx_period_return']].copy()

# save out to excel
spx_excel_intraday.to_excel("../data/intermediate_input/spx_intraday_returns.xlsx", index=False)

## Back-Test Volatility Control Strategies

**The following analysis will compare a number of different strategies for exposure to the S&P 500:**
1. Buying and holding the SPDR S&P 500 ETF (SPY) over the period
2. A baseline intraday volatility control strategy using the S&P 500 Dynamic Intraday TCA Index Methodology (Controls index exposure through futures)
3. A refined volatility control strategy using the S&P 500 Intraday Edge Macro Indices methodology
4. A volatility control strategy using intraday volatility forecasts from the Bayesian Joint Quantile Time Series Model For Asset Returns

### Import and clean the S&P 500 Intraday Indices data (comparison)

#### Import the intraday indices data

In [35]:
intraday_index_levels = pd.read_excel("../data/input/intraday_indices_levels.xlsx")

#### Clean the data

##### Correct the columns and column names

In [36]:
# set the columns to correctly be the items in the 6th row
intraday_index_levels.columns = intraday_index_levels.iloc[5]

#drop all those rows not needed anymore
intraday_index_levels = intraday_index_levels.drop(index=[0,1,2,3,4,5]).reset_index().drop('index', axis=1)

# change the column names to be in lowercase with underscores instead of spaces
intraday_index_levels.columns = [col.lower().replace(' ', '_') for col in intraday_index_levels.columns]
                                 
# remove "&" and ( or ) from column names
intraday_index_levels.columns = [col.replace('&', '') for col in intraday_index_levels.columns]
intraday_index_levels.columns = [col.replace('(', '') for col in intraday_index_levels.columns]
intraday_index_levels.columns = [col.replace(')', '') for col in intraday_index_levels.columns]

intraday_index_levels

,effective_date_,sp_500_dynamic_intraday_tca_index_usd_er,sp_500_futures_index_er,sp_500_futures_12%_intraday_edge_growth_tca_usd_er,sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er,sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er
0,2015-12-31 00:00:00,100,100,100,100,100
1,2016-01-04 00:00:00,98.26,98.7,98.09,99.47,99.12
2,2016-01-05 00:00:00,98.47,98.83,98.35,99.62,99.18
3,2016-01-06 00:00:00,97.64,97.57,97.46,99.53,98.75
4,2016-01-07 00:00:00,96.36,94.96,96.52,99.35,98.09
...,...,...,...,...,...,...
2529,2026-01-22 00:00:00,328.51,306.44,326.99,219.79,202.39
2530,NaN,NaN,NaN,NaN,NaN,NaN
2531,NaN,NaN,NaN,NaN,NaN,NaN
2532,NaN,NaN,NaN,NaN,NaN,NaN
2533,DISCLAIMER\n\nPERFORMANCE DISCLOSURE/BACK-TEST...,NaN,NaN,NaN,NaN,NaN

##### Change the columns to be of the correct formats

In [37]:
# correct the date column to datetime format
intraday_index_levels_v1 = intraday_index_levels.copy()

intraday_index_levels_v1["effective_date_"] = pd.to_datetime(
    intraday_index_levels_v1["effective_date_"],
    errors="coerce"   # invalid strings -> NaT instead of crashing
)
# drop rows with NaT in effective_date_ column
intraday_index_levels_v1 = intraday_index_levels_v1.dropna(subset=["effective_date_"])

In [38]:
intraday_index_levels_v2 = intraday_index_levels_v1.copy()

# rename the date column to be 'time', and
# rename the remaining columns to have 'level' on the end
intraday_index_levels_v2.columns = ['time'] + [f"{col}_level" for col in intraday_index_levels_v2.columns if "sp" in col]

# correct the level columns to be float format

level_columns = [col for col in intraday_index_levels_v2.columns if 'level' in col]
for col in level_columns:
    intraday_index_levels_v2[col] = pd.to_numeric(intraday_index_levels_v2[col], errors='coerce')

In [39]:
intraday_index_levels_v2

,time,sp_500_dynamic_intraday_tca_index_usd_er_level,sp_500_futures_index_er_level,sp_500_futures_12%_intraday_edge_growth_tca_usd_er_level,sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er_level,sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er_level
0,2015-12-31,100.00,100.00,100.00,100.00,100.00
1,2016-01-04,98.26,98.70,98.09,99.47,99.12
2,2016-01-05,98.47,98.83,98.35,99.62,99.18
3,2016-01-06,97.64,97.57,97.46,99.53,98.75
4,2016-01-07,96.36,94.96,96.52,99.35,98.09
...,...,...,...,...,...,...
2525,2026-01-15,335.16,308.06,329.58,218.82,203.64
2526,2026-01-16,335.07,307.84,329.65,217.76,203.51
2527,2026-01-20,322.00,301.34,322.70,218.15,200.75
2528,2026-01-21,327.07,304.89,325.55,219.29,201.71
2529,2026-01-22,328.51,306.44,326.99,219.79,202.39

#### Add log return and cumulative return columns for these indices

In [40]:
# run an instance of the ReturnsCalculator class from the returns.py module to compute log returns
calc = ReturnsCalculator(ReturnsConfig(return_kind="log", inplace=False))

# run the transform method of the ReturnsCalculator instance to compute the returns
intraday_index_levels_v3 = calc.transform(intraday_index_levels_v2)

In [41]:
intraday_index_levels_v3

,time,sp_500_dynamic_intraday_tca_index_usd_er_level,sp_500_futures_index_er_level,sp_500_futures_12%_intraday_edge_growth_tca_usd_er_level,sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er_level,sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er_level,sp_500_dynamic_intraday_tca_index_usd_er_period_return,sp_500_dynamic_intraday_tca_index_usd_er_total_return,sp_500_futures_index_er_period_return,sp_500_futures_index_er_total_return,sp_500_futures_12%_intraday_edge_growth_tca_usd_er_period_return,sp_500_futures_12%_intraday_edge_growth_tca_usd_er_total_return,sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er_period_return,sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er_total_return,sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er_period_return,sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er_total_return
0,2015-12-31,100.00,100.00,100.00,100.00,100.00,NaN,0.000000,NaN,0.0000,NaN,0.000000,NaN,0.000000,NaN,0.000000
1,2016-01-04,98.26,98.70,98.09,99.47,99.12,-0.017553,-0.017400,-0.013085,-0.0130,-0.019285,-0.019100,-0.005314,-0.005300,-0.008839,-0.008800
2,2016-01-05,98.47,98.83,98.35,99.62,99.18,0.002135,-0.015300,0.001316,-0.0117,0.002647,-0.016500,0.001507,-0.003800,0.000605,-0.008200
3,2016-01-06,97.64,97.57,97.46,99.53,98.75,-0.008465,-0.023600,-0.012831,-0.0243,-0.009091,-0.025400,-0.000904,-0.004700,-0.004345,-0.012500
4,2016-01-07,96.36,94.96,96.52,99.35,98.09,-0.013196,-0.036400,-0.027114,-0.0504,-0.009692,-0.034800,-0.001810,-0.006500,-0.006706,-0.019100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2525,2026-01-15,335.16,308.06,329.58,218.82,203.64,0.005565,2.392880,0.002210,2.0806,0.003069,2.324659,-0.002237,1.174498,0.002065,1.049410
2526,2026-01-16,335.07,307.84,329.65,217.76,203.51,-0.000269,2.391969,-0.000714,2.0784,0.000212,2.325365,-0.004856,1.163965,-0.000639,1.048102
2527,2026-01-20,322.00,301.34,322.70,218.15,200.75,-0.039788,2.259660,-0.021341,2.0134,-0.021308,2.255256,0.001789,1.167840,-0.013655,1.020325
2528,2026-01-21,327.07,304.89,325.55,219.29,201.71,0.015623,2.310984,0.011712,2.0489,0.008793,2.284006,0.005212,1.179169,0.004771,1.029987
2529,2026-01-22,328.51,306.44,326.99,219.79,202.39,0.004393,2.325561,0.005071,2.0644,0.004414,2.298532,0.002277,1.184138,0.003366,1.036830

### EDA of the intraday indices data

#### Plot the S&P 500 Intraday Indices levels

##### Plot setup

In [42]:
# Specify the correct columns that we want to plot:
# all the columns that have 'period_return' in their name

index_levels_cols = [col for col in intraday_index_levels_v3.columns if 'level' in col]

index_levels_cols

['sp_500_dynamic_intraday_tca_index_usd_er_level',
 'sp_500_futures_index_er_level',
 'sp_500_futures_12%_intraday_edge_growth_tca_usd_er_level',
 'sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er_level',
 'sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er_level']

In [43]:
# add a colour map
# start with light blue to purple gradient for the different level series
gen = GradientColourMap(index_levels_cols, start="cyan", end="purple")
index_levels_colour_map = gen.run()          # or gen.run(); colour_map_values = gen.colour_map

##### Plot display

In [44]:
# enter those parameters into the dash app that creates the plot
cfg = LevelAppConfig(
    cols_of_interest=index_levels_cols,
    reindex=True,
    colour_map=index_levels_colour_map,
    title="Comparison of Index Levels",
    figure_title="Index Levels over Selected Period",
    fig_height=800,
    port=8053,
)

# run the app (produce the plot)
dash_app = LevelDashApp(intraday_index_levels_v3, cfg)
dash_app.run(debug=True)

#### Plot the S&P 500 Intraday Indices returns

##### Plot setup

In [45]:
# Specify the correct columns that we want to plot:
# all the columns that have 'period_return' in their name

index_returns_cols = [col for col in intraday_index_levels_v3.columns if 'period_return' in col]

index_returns_cols

['sp_500_dynamic_intraday_tca_index_usd_er_period_return',
 'sp_500_futures_index_er_period_return',
 'sp_500_futures_12%_intraday_edge_growth_tca_usd_er_period_return',
 'sp_multi-asset_5%_intraday_edge_macro_tca_index_usd_er_period_return',
 'sp_500_futures_7%_intraday_edge_volatility_tca_index__usd_er_period_return']

In [46]:
# add a colour map
# start with light blue to purple gradient for the different level series
gen = GradientColourMap(index_returns_cols, start="cyan", end="purple")
index_returns_colour_map = gen.run()          # or gen.run(); colour_map_values = gen.colour_map

##### Plot display

In [47]:
# hardcode re-import of the visualisation dash app if needed
#import src.stats_utils.dash_timeseries_app as dta
#importlib.reload(dta)

In [48]:
# enter those parameters into the dash app that creates the plot
cfg = dta.LevelAppConfig(
    cols_of_interest=index_returns_cols,
    reindex=False,
    title="Comparison of Index Returns",
    figure_title="Index Returns over Selected Period",
    fig_height=800,
    port=8054,
)

# run the app (produce the plot)
dash_app = dta.LevelDashApp(intraday_index_levels_v3, cfg)
dash_app.run(
    debug=False
)

## Compare Performance of Different Srategies

#### Create a Function to Save the Performance Summary Statistics to Excel Nicely

In [49]:
def save_with_bold_highlights(summary_stats, filename):
    # Identify metric pairs (assume every two columns after the first two are a pair)
    cols = summary_stats.columns.tolist()
    pairs = [(cols[i], cols[i+1]) for i in range(2, len(cols), 2)]
    volatility_keywords = ['volatility']
    sharpe_keywords = ['sharpe']

    with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
        summary_stats.to_excel(writer, index=False)
        workbook  = writer.book
        worksheet = writer.sheets['Sheet1']
        bold = workbook.add_format({'bold': True})

        for row in range(1, len(summary_stats)+1):  # +1 for header
            for col1, col2 in pairs:
                idx1 = cols.index(col1)
                idx2 = cols.index(col2)
                val1 = summary_stats.iloc[row-1, idx1]
                val2 = summary_stats.iloc[row-1, idx2]
                metric = col1.lower()

                # For volatility, lower is better
                if any(key in metric for key in volatility_keywords):
                    if val1 < val2:
                        worksheet.write(row, idx1, val1, bold)
                    elif val2 < val1:
                        worksheet.write(row, idx2, val2, bold)
                # For Sharpe, ignore if both negative
                elif any(key in metric for key in sharpe_keywords):
                    if val1 >= 0 and val1 > val2:
                        worksheet.write(row, idx1, val1, bold)
                    elif val2 >= 0 and val2 > val1:
                        worksheet.write(row, idx2, val2, bold)
                # For all other metrics, higher is better
                else:
                    if val1 > val2:
                        worksheet.write(row, idx1, val1, bold)
                    elif val2 > val1:
                        worksheet.write(row, idx2, val2, bold)

        # writer.save()

#### Create a Function to Calculate Performance Metrics

In [50]:
class PerformanceSummary:
    """
    Compute performance summary statistics for multiple return series.

    Usage:
        ps = PerformanceSummary(df, ret_cols, kind="log")
        summary = ps.run()
    """

    def __init__(
        self,
        df: pd.DataFrame,
        ret_cols,
        kind: str = "simple",
        *,
        include_vol: bool = False,
        include_drawdown: bool = False,
        periods_per_year: float = 252.0, # default 252 for interday data
    ):
        """
        Initialize with DataFrame, return columns, and return type.
        Done to make attributes retrievable later and clearly associated with the instance.
        """
        self.df = df # dataframe input
        self.x = None  # prepared dataframe (filled in _prepare_returns)
        self.R = None # returns dataframe (filled in _prepare_returns)
        self.ret_cols = list(ret_cols)
        self.kind = kind
        self.include_vol = include_vol
        self.include_drawdown = include_drawdown
        self.periods_per_year = periods_per_year

        # filled during run()
        self.summary = None

    def _prepare_returns(self) -> pd.DataFrame:
        """
        Prepare the returns DataFrame for analysis.
        Convert the 'time' column to datetime, sort by time, and set it as the index.
        Return only the specified return columns as floats.
        """
        # create an attribute self.x to hold the prepared DataFrame
        self.x = self.df.copy() # make a copy to avoid modifying original
        self.x["time"] = pd.to_datetime(self.x["time"])
        self.x = self.x.sort_values("time").set_index("time")
        # return only the return columns as float type,
        # now indexed by time thanks to the above code
        return self.x[self.ret_cols].astype(float)

    def _total_return(self, frame: pd.DataFrame) -> pd.Series:
        """Calculate total return  over the given DataFrame frame."""
        # using log returns 
        if self.kind == "log":
            return np.exp(frame.sum()) - 1
        # using simple returns
        else:
            return (1 + frame).prod() - 1
        
    def _equity_curve(self, frame: pd.DataFrame) -> pd.DataFrame:
        """Equity curve starting at 1.0 for each column."""
        if self.kind == "log":
            return np.exp(frame.cumsum())
        else:
            return (1 + frame).cumprod()
        
    def _annualised_vol(self, frame: pd.DataFrame) -> pd.Series:
        """Annualised volatility per column."""
        # the ddof=0 gives population std dev, ddof=1 gives sample std dev
        if self.kind == "log":
            r = frame
        else:
            r = np.log1p(frame)  # log(1+r)
        return r.std(ddof=0) * np.sqrt(self.periods_per_year)

    def _max_drawdown(self, frame: pd.DataFrame) -> pd.Series:
        """Max drawdown (most negative) per column over the window."""
        # start with equity curve
        eq = self._equity_curve(frame)
        # then calculate the drawdown: the largest % drop in equity from a prior peak
        dd = eq / eq.cummax() - 1.0
        return dd.min()
    
    def _add_extra_stats(self, row: dict, frame: pd.DataFrame) -> dict:
        """Add extra statistics like volatility and drawdown to the stats Series."""
        # add extra stats if requested by user
        if self.include_vol:
            # find the value of annualised volatility
            vol = self._annualised_vol(frame)
            # store as e.g. "spx_vol", "es_vol" etc.
            row.update({f"{c}_vol": float(vol[c]) for c in self.ret_cols})
        if self.include_drawdown:
            # find the value of max drawdown
            mdd = self._max_drawdown(frame) 
            # add to the row as e.g. "spx_max_drawdown", "es_max_drawdown" etc.
            row.update({f"{c}_max_drawdown": float(mdd[c]) for c in self.ret_cols})
        return row

    def run(self) -> pd.DataFrame:
        """
        Compute performance summary statistics by calling on the above functions
        """
        # prepare returns DataFrame by calling _prepare_returns
        # which sets up the time index and selects return columns
        self.R = self._prepare_returns()

        # 1) calendar-year totals
            # resamples by year end, since .resample("Y") uses Dec 31 as year end by default
            # and groups rows into calendar year buckets
        yearly = self._total_return(self.R.resample("YE"))

        
            

        out = yearly.reset_index()
        out["period"] = out["time"].dt.year.astype(str) # add a label for the period
        
        # add start and end dates for the window
        out["start_date"] = out["time"].dt.year.astype(str) + "-01-01"
        out["end_date"]   = out["time"].dt.year.astype(str) + "-12-31"

        # add extra stats if requested: but iterative so slower
        if self.include_vol or self.include_drawdown:
            extra_rows = []
            for year_end, frame in self.R.resample("YE"):
                extra = {"period": str(year_end.year)}
                extra = self._add_extra_stats(extra, frame)
                extra_rows.append(extra)

            extra_df = pd.DataFrame(extra_rows)
            # combine with original out dataframe
            out = out.merge(extra_df, on="period", how="left")



        # sort in descending order of year
        out = out.sort_values("period", ascending=False)
        out = out.drop(columns=["time"]) # drop the time column as no longer needed

        # 2) YTD
        last_date = self.R.index.max()
        ytd = self._total_return(self.R.loc[f"{last_date.year}-01-01":last_date])

        ytd_row = {
            "period": "YTD",
            "start_date": f"{last_date.year}-01-01",
            "end_date": str(last_date.date()),
            # the ** operator unpacks the series into a dict, because it detects that 
            # the indices of the series (returns series we were comparing against) 
            # correspond to the keys expected in the dict
            **ytd.to_dict() 
        }

        # add extra stats if requested
        ytd_row = self._add_extra_stats(ytd_row, self.R.loc[f"{last_date.year}-01-01":last_date])
        ytd_df = pd.DataFrame([ytd_row])

        # 3) rolling multi-year windows
        window_rows = []
        for window in (1, 3, 5, 10):
            # compute start date for the rolling window to be the last date for which
            # we have data, minus the window length
            start = last_date - pd.DateOffset(years=window)
            # make sure the start date is not before the first date in the data
            start = max(start, self.R.index.min())

            # compute stats for the slice of the dataframe corresponding to this window
            frame = self.R.loc[start:last_date]
            stats = self._total_return(frame)

            # annualise the returns
            elapsed_years = (frame.index[-1] - frame.index[0]).days / 365.25
            stats = (1 + stats) ** (1 / elapsed_years) - 1


            row = {
                "period": f"Last{window} Years",
                "start_date": str(start.date()),
                "end_date": str(last_date.date()),
                # the ** operator unpacks the series into a dict, because it detects that 
                # the indices of the series (returns series we were comparing against) 
                # correspond to the keys expected in the dict
                **stats.to_dict() 
            }

            # add extra stats if requested
            row = self._add_extra_stats(row, frame)            

            # append the row to the list of window rows
            window_rows.append(row)

        windows_df = pd.DataFrame(window_rows)

        summary = pd.concat([ytd_df, windows_df, out], ignore_index=True)

        # formatting
        # ensure the numeric cols are stored as floats but rounded to 4 decimal places
        for c in [col for col in summary.columns if col not in ["period", "start_date", "end_date"]]:
            summary[c] = summary[c].astype(float).round(4)

        # format the summary columns neatly in title format without underscores
        summary.columns = [c.replace("_", " ").title() for c in summary.columns]

        self.summary = summary
        return summary

In [ ]:
# hardcode backup for reloading the performance module
#importlib.reload(pm)
# from src.stats_utils.performance import PerformanceSummary

<module 'src.stats_utils.performance' from 'c:\\Users\\danie\\OneDrive\\Desktop\\Github_Pages\\Risk-Control-Using-a-Bayesian-Joint-Quantile-Time-Series-Model-For-Asset-Returns\\src\\stats_utils\\performance.py'>

In [68]:
# set up the configuration for the performance summary
ps = pm.PerformanceSummary(
    intraday_index_levels_v3,
    index_returns_cols,
    kind="log",
    annualise = ["YTD","windows","resampled"],
    # set resampling frequency to quarterly
    resample_freq="Q",
    include_vol=True,
    include_drawdown=True,
    periods_per_year=252,
)

# run the performance summary calculation
strategies_performance_summary_df = ps.run()

# inspect the summary dataframe
strategies_performance_summary_df

<string>:8: FutureWarning:

'Q' is deprecated and will be removed in a future version, please use 'QE' instead.

,Period,Start Date,End Date,Sp 500 Dynamic Intraday Tca Index Usd Er Period Return,Sp 500 Futures Index Er Period Return,Sp 500 Futures 12% Intraday Edge Growth Tca Usd Er Period Return,Sp Multi-Asset 5% Intraday Edge Macro Tca Index Usd Er Period Return,Sp 500 Futures 7% Intraday Edge Volatility Tca Index Usd Er Period Return,Sp 500 Dynamic Intraday Tca Index Usd Er Period Return Volatility,Sp 500 Futures Index Er Period Return Volatility,...,Sp 500 Dynamic Intraday Tca Index Usd Er Period Return Sharpe,Sp 500 Futures Index Er Period Return Sharpe,Sp 500 Futures 12% Intraday Edge Growth Tca Usd Er Period Return Sharpe,Sp Multi-Asset 5% Intraday Edge Macro Tca Index Usd Er Period Return Sharpe,Sp 500 Futures 7% Intraday Edge Volatility Tca Index Usd Er Period Return Sharpe,Sp 500 Dynamic Intraday Tca Index Usd Er Period Return Max Drawdown,Sp 500 Futures Index Er Period Return Max Drawdown,Sp 500 Futures 12% Intraday Edge Growth Tca Usd Er Period Return Max Drawdown,Sp Multi-Asset 5% Intraday Edge Macro Tca Index Usd Er Period Return Max Drawdown,Sp 500 Futures 7% Intraday Edge Volatility Tca Index Usd Er Period Return Max Drawdown
0,YTD,2026-01-01,2026-01-22,0.0129,0.1489,0.0737,0.2821,0.0663,0.2106,0.1187,...,0.0611,1.2542,0.5788,5.6708,0.8360,-0.0489,-0.0266,-0.0293,-0.0071,-0.0186
1,Last 1 Years,2025-01-22,2026-01-22,0.0253,0.1019,0.0750,0.1263,0.0410,0.1478,0.1838,...,0.1710,0.5547,0.6370,2.5290,0.5970,-0.1371,-0.1929,-0.1036,-0.0236,-0.0643
2,Last 3 Years,2023-01-22,2026-01-22,0.1243,0.1547,0.1510,0.0874,0.0948,0.1500,0.1485,...,0.8286,1.0415,1.2622,1.8048,1.3624,-0.1577,-0.1938,-0.1197,-0.0381,-0.0659
3,Last 5 Years,2021-01-22,2026-01-22,0.0656,0.0975,0.1087,0.0724,0.0639,0.1494,0.1684,...,0.4390,0.5788,0.8955,1.4855,0.8970,-0.2111,-0.2522,-0.1615,-0.0568,-0.1027
4,Last 10 Years,2016-01-22,2026-01-22,0.1354,0.1285,0.1344,0.0830,0.0773,0.1479,0.1786,...,0.9152,0.7196,1.1304,1.6802,1.1049,-0.2111,-0.3415,-0.1615,-0.0605,-0.1027
5,2026Q1,2026-01-01,2026-12-31,0.0029,0.0317,0.0161,0.0574,0.0145,0.2106,0.1187,...,0.0137,0.2669,0.1265,1.1545,0.1832,-0.0489,-0.0266,-0.0293,-0.0071,-0.0186
6,2025Q4,2025-01-01,2025-12-31,-0.1211,0.0571,-0.0648,0.0909,-0.0645,0.1421,0.1848,...,-0.8526,0.3091,-0.5535,1.8533,-0.9518,-0.1371,-0.1929,-0.1036,-0.0236,-0.0643
7,2025Q3,2025-01-01,2025-12-31,0.3864,0.3039,0.3961,0.2365,0.2288,0.1421,0.1848,...,2.7199,1.6444,3.3846,4.8210,3.3742,-0.1371,-0.1929,-0.1036,-0.0236,-0.0643
8,2025Q2,2025-01-01,2025-12-31,0.2630,0.4534,0.4096,0.0646,0.2355,0.1421,0.1848,...,1.8511,2.4531,3.4997,1.3167,3.4730,-0.1371,-0.1929,-0.1036,-0.0236,-0.0643
9,2025Q1,2025-01-01,2025-12-31,-0.1761,-0.2117,-0.1839,0.0967,-0.1075,0.1421,0.1848,...,-1.2397,-1.1455,-1.5711,1.9710,-1.5854,-0.1371,-0.1929,-0.1036,-0.0236,-0.0643
10,2024Q4,2024-01-01,2024-12-31,-0.0742,0.0374,-0.1111,-0.0592,-0.0048,0.1540,0.1259,...,-0.4817,0.2969,-0.9108,-1.1978,-0.0691,-0.0958,-0.0874,-0.0598,-0.0308,-0.0330
11,2024Q3,2024-01-01,2024-12-31,0.0928,0.1781,0.3427,0.1437,0.1757,0.1540,0.1259,...,0.6027,1.4145,2.8092,2.9067,2.5226,-0.0958,-0.0874,-0.0598,-0.0308,-0.0330
12,2024Q2,2024-01-01,2024-12-31,0.1086,0.1179,0.1807,0.0883,0.0995,0.1540,0.1259,...,0.7052,0.9359,1.4810,1.7860,1.4286,-0.0958,-0.0874,-0.0598,-0.0308,-0.0330
13,2024Q1,2024-01-01,2024-12-31,0.5171,0.4074,0.4325,0.2057,0.2469,0.1540,0.1259,...,3.3587,3.2350,3.5453,4.1613,3.5447,-0.0958,-0.0874,-0.0598,-0.0308,-0.0330
14,2023Q4,2023-01-01,2023-12-31,0.6406,0.4752,0.4849,0.0898,0.2944,0.1490,0.1305,...,4.2989,3.6417,4.0729,1.9223,4.1039,-0.1422,-0.1132,-0.1105,-0.0381,-0.0659
15,2023Q3,2023-01-01,2023-12-31,-0.2537,-0.1751,-0.2188,-0.0647,-0.1335,0.1490,0.1305,...,-1.7024,-1.3416,-1.8378,-1.3850,-1.8604,-0.1422,-0.1132,-0.1105,-0.0381,-0.0659
16,2023Q2,2023-01-01,2023-12-31,0.4740,0.3346,0.3658,0.1303,0.2075,0.1490,0.1305,...,3.1811,2.5643,3.0720,2.7867,2.8924,-0.1422,-0.1132,-0.1105,-0.0381,-0.0659
17,2023Q1,2023-01-01,2023-12-31,0.1550,0.2805,0.2547,0.0671,0.1366,0.1490,0.1305,...,1.0404,2.1498,2.1394,1.4351,1.9037,-0.1422,-0.1132,-0.1105,-0.0381,-0.0659
18,2022Q4,2022-01-01,2022-12-31,0.1788,0.2801,0.2121,0.1692,0.0570,0.1489,0.2401,...,1.2003,1.1665,1.7551,3.5397,0.8190,-0.1856,-0.2522,-0.1605,-0.0568,-0.1011
19,2022Q3,2022-01-01,2022-12-31,-0.0711,-0.1993,-0.0281,0.0335,0.0251,0.1489,0.2401,...,-0.4775,-0.8301,-0.2323,0.6999,0.3607,-0.1856,-0.2522,-0.1605,-0.0568,-0.1011
20,2022Q2,2022-01-01,2022-12-31,-0.3430,-0.5165,-0.2913,-0.1596,-0.1749,0.1489,0.2401,...,-2.3029,-2.1510,-2.4104,-3.3394,-2.5128,-0.1856,-0.2522,-0.1605,-0.0568,-0.1011
21,2022Q1,2022-01-01,2022-12-31,-0.2762,-0.1751,-0.2221,0.1323,-0.1601,0.1489,0.2401,...,-1.8544,-0.7291,-1.8384,2.7672,-2.2991,-0.1856,-0.2522,-0.1605,-0.0568,-0.1011
22,2021Q4,2021-01-01,2021-12-31,0.2638,0.5147,0.5022,0.1791,0.2146,0.1510,0.1299,...,1.7464,3.9623,3.9387,3.5013,2.8233,-0.0908,-0.0518,-0.0569,-0.0251,-0.0291
23,2021Q3,2021-01-01,2021-12-31,-0.1589,0.0170,-0.0008,-0.0163,0.0368,0.1510,0.1299,...,-1.0519,0.1312,-0.0060,-0.3189,0.4836,-0.0908,-0.0518,-0.0569,-0.0251,-0.0291
24,2021Q2,2021-01-01,2021-12-31,0.4092,0.3834,0.4190,0.1111,0.2007,0.1510,0.1299,...,2.7095,2.9511,3.2864,2.1720,2.6410,-0.0908,-0.0518,-0.0569,-0.0251,-0.0291
25,2021Q1,2021-01-01,2021-12-31,0.1405,0.2747,0.0531,-0.0027,0.0276,0.1510,0.1299,...,0.9302,2.1145,0.4162,-0.0525,0.3633,-0.0908,-0.0518,-0.0569,-0.0251,-0.0291
26,2020Q4,2020-01-01,2020-12-31,0.2172,0.5801,0.1288,0.0300,0.1210,0.1557,0.3308,...,1.3949,1.7536,1.0487,0.6044,1.6510,-0.1192,-0.3415,-0.0950,-0.0334,-0.0525
27,2020Q3,2020-01-01,2020-12-31,0.3341,0.4036,0.2705,0.1241,0.1704,0.1557,0.3308,...,2.1461,1.2202,2.2025,2.4986,2.3250,-0.1192,-0.3415,-0.0950,-0.0334,-0.0525
28,2020Q2,2020-01-01,2020-12-31,0.4204,1.1449,0.1731,0.0863,0.1032,0.1557,0.3308,...,2.7004,3.4611,1.4096,1.7377,1.4084,-0.1192,-0.3415,-0.0950,-0.0334,-0.0525
29,2020Q1,2020-01-01,2020-12-31,-0.1438,-0.5979,-0.0977,0.2825,-0.0812,0.1557,0.3308,...,-0.9238,-1.8074,-0.7951,5.6876,-1.1073,-0.1192,-0.3415,-0.0950,-0.0334,-0.0525
30,2019Q4,2019-01-01,2019-12-31,0.5074,0.3806,0.4472,0.1671,0.2885,0.1331,0.1298,...,3.8115,2.9328,3.8588,3.4356,4.1196,-0.0860,-0.0675,-0.0979,-0.0300,-0.0487
31,2019Q3,2019-01-01,2019-12-31,0.0140,0.0445,-0.0905,-0.0113,-0.0749,0.1331,0.1298,...,0.1050,0.3432,-0.7812,-0.2324,-1.0692,-0.0860,-0.0675,-0.0979,-0.0300,-0.0487
32,2019Q2,2019-01-01,2019-12-31,0.1682,0.1543,0.0687,0.1398,0.0690,0.1331,0.1298,...,1.2638,1.1890,0.5928,2.8738,0.9854,-0.0860,-0.0675,-0.0979,-0.0300,-0.0487
33,2019Q1,2019-01-01,2019-12-31,0.5381,0.6555,0.4762,0.2154,0.2309,0.1331,0.1298,...,4.0421,5.0508,4.1090,4.4286,3.2962,-0.0860,-0.0675,-0.0979,-0.0300,-0.0487
34,2018Q4,2018-01-01,2018-12-31,-0.5256,-0.4615,-0.3522,-0.0798,-0.2265,0.1566,0.1755,...,-3.3560,-2.6299,-2.8961,-1.5577,-3.0512,-0.1961,-0.2044,-0.1207,-0.0605,-0.0785
35,2018Q3,2018-01-01,2018-12-31,0.4855,0.3151,0.3512,0.0135,0.2318,0.1566,0.1755,...,3.1001,1.7958,2.8879,0.2626,3.1214,-0.1961,-0.2044,-0.1207,-0.0605,-0.0785
36,2018Q2,2018-01-01,2018-12-31,0.0914,0.1200,0.0182,-0.0273,0.0069,0.1566,0.1755,...,0.5838,0.6836,0.1493,-0.5320,0.0928,-0.1961,-0.2044,-0.1207,-0.0605,-0.0785
37,2018Q1,2018-01-01,2018-12-31,0.1982,-0.0562,0.1384,0.0959,0.0622,0.1566,0.1755,...,1.2655,-0.3202,1.1384,1.8706,0.8379,-0.1961,-0.2044,-0.1207,-0.0605,-0.0785
38,2017Q4,2017-01-01,2017-12-31,0.7133,0.2747,0.4926,0.2247,0.2312,0.1363,0.0630,...,5.2348,4.3618,4.7117,4.6626,3.9781,-0.0573,-0.0262,-0.0485,-0.0188,-0.0264
39,2017Q3,2017-01-01,2017-12-31,0.3565,0.1702,0.2952,0.1167,0.1467,0.1363,0.0630,...,2.6162,2.7026,2.8234,2.4206,2.5243,-0.0573,-0.0262,-0.0485,-0.0188,-0.0264
40,2017Q2,2017-01-01,2017-12-31,0.2122,0.1149,0.1222,0.0352,0.0644,0.1363,0.0630,...,1.5573,1.8255,1.1685,0.7303,1.1074,-0.0573,-0.0262,-0.0485,-0.0188,-0.0264
41,2017Q1,2017-01-01,2017-12-31,0.6317,0.2527,0.4290,0.2191,0.2114,0.1363,0.0630,...,4.6359,4.0127,4.1033,4.5457,3.6368,-0.0573,-0.0262,-0.0485,-0.0188,-0.0264
42,2016Q4,2016-01-01,2016-12-31,0.2311,0.1593,0.1503,-0.0560,0.0605,0.1445,0.1315,...,1.5993,1.2110,1.2900,-1.1060,0.9152,-0.0793,-0.0931,-0.0725,-0.0429,-0.0430
43,2016Q3,2016-01-01,2016-12-31,0.1034,0.1564,0.1690,0.0324,0.0552,0.1445,0.1315,...,0.7153,1.1891,1.4510,0.6405,0.8350,-0.0793,-0.0931,-0.0725,-0.0429,-0.0430
44,2016Q2,2016-01-01,2016-12-31,-0.0431,0.0980,0.1263,0.1563,0.1014,0.1445,0.1315,...,-0.2983,0.7452,1.0846,3.0845,1.5350,-0.0793,-0.0931,-0.0725,-0.0429,-0.0430
45,2016Q1,2016-01-01,2016-12-31,0.0777,0.0521,-0.0726,0.1133,0.0016,0.1445,0.1315,...,0.5374,0.3963,-0.6233,2.2366,0.0246,-0.0793,-0.0931,-0.0725,-0.0429,-0.0430
46,2015Q4,2015-01-01,2015-12-31,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
# save out to excel
strategies_performance_summary_df.to_excel("../data/intermediate_input/summary_stats2.xlsx", index=False)

In [84]:
pc = pm.PerformanceCompare(
    strategies_performance_summary_df)

transformed_df = pc._transform_summary_df()

In [77]:
transformed_df

Period                                           strategy_name       2015Q4  \
metric_type                                                    Total Return
0                     Sp 500 Dynamic Intraday Tca Index Usd Er          0.0
1            Sp 500 Futures 12% Intraday Edge Growth Tca Us...          0.0
2            Sp 500 Futures 7% Intraday Edge Volatility Tca...          0.0
3                                      Sp 500 Futures Index Er          0.0
4            Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...          0.0

Period            2016Q1                                       2016Q2          \
metric_type Max Drawdown  Sharpe Total Return Volatility Max Drawdown  Sharpe
0                -0.0793  0.5374       0.0777     0.1445      -0.0793 -0.2983
1                -0.0725 -0.6233      -0.0726     0.1165      -0.0725  1.0846
2                -0.0430  0.0246       0.0016     0.0661      -0.0430  1.5350
3                -0.0931  0.3963       0.0521     0.1315      -0.0931  0.7452
4                -0.0429  2.2366       0.1133     0.0507      -0.0429  3.0845

Period                               ... Last 3 Years            Last 5 Years  \
metric_type Total Return Volatility  ... Total Return Volatility Max Drawdown
0                -0.0431     0.1445  ...       0.1243     0.1500      -0.2111
1                 0.1263     0.1165  ...       0.1510     0.1196      -0.1615
2                 0.1014     0.0661  ...       0.0948     0.0696      -0.1027
3                 0.0980     0.1315  ...       0.1547     0.1485      -0.2522
4                 0.1563     0.0507  ...       0.0874     0.0484      -0.0568

Period                                               YTD                       \
metric_type  Sharpe Total Return Volatility Max Drawdown  Sharpe Total Return
0            0.4390       0.0656     0.1494      -0.0489  0.0611       0.0129
1            0.8955       0.1087     0.1214      -0.0293  0.5788       0.0737
2            0.8970       0.0639     0.0712      -0.0186  0.8360       0.0663
3            0.5788       0.0975     0.1684      -0.0266  1.2542       0.1489
4            1.4855       0.0724     0.0487      -0.0071  5.6708       0.2821

Period
metric_type Volatility
0               0.2106
1               0.1273
2               0.0793
3               0.1187
4               0.0497

[5 rows x 186 columns]

In [92]:
pc.run()

Complete
Complete
Complete
Complete

,Ranked by Total Return (Last 5 Years),Total Return (Last 5 Years),Ranked by Total Return (Last 10 Years),Total Return (Last 10 Years),Ranked by Sharpe (Last 5 Years),Sharpe (Last 5 Years),Ranked by Sharpe (Last 10 Years),Sharpe (Last 10 Years)
0,Sp 500 Futures 12% Intraday Edge Growth Tca Us...,0.1087,Sp 500 Dynamic Intraday Tca Index Usd Er,0.1354,Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...,1.4855,Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...,1.6802
1,Sp 500 Futures Index Er,0.0975,Sp 500 Futures 12% Intraday Edge Growth Tca Us...,0.1344,Sp 500 Futures 7% Intraday Edge Volatility Tca...,0.8970,Sp 500 Futures 12% Intraday Edge Growth Tca Us...,1.1304
2,Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...,0.0724,Sp 500 Futures Index Er,0.1285,Sp 500 Futures 12% Intraday Edge Growth Tca Us...,0.8955,Sp 500 Futures 7% Intraday Edge Volatility Tca...,1.1049
3,Sp 500 Dynamic Intraday Tca Index Usd Er,0.0656,Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...,0.0830,Sp 500 Futures Index Er,0.5788,Sp 500 Dynamic Intraday Tca Index Usd Er,0.9152
4,Sp 500 Futures 7% Intraday Edge Volatility Tca...,0.0639,Sp 500 Futures 7% Intraday Edge Volatility Tca...,0.0773,Sp 500 Dynamic Intraday Tca Index Usd Er,0.4390,Sp 500 Futures Index Er,0.7196

In [ ]:
strategy_rankings_dfs[('Total Return','Last5 Years')]

  Total Return (Last5 Years)  \

0                     0.1087
1                     0.0975
2                     0.0724
3                     0.0656
4                     0.0639

                                       strategy_name         2015  \
                                                     Total Return
0  Sp 500 Futures 12% Intraday Edge Growth Tca Us...          0.0
1                            Sp 500 Futures Index Er          0.0
2  Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...          0.0
3           Sp 500 Dynamic Intraday Tca Index Usd Er          0.0
4  Sp 500 Futures 7% Intraday Edge Volatility Tca...          0.0

          2016                                      2017                       \
  Max Drawdown  Sharpe Total Return     Vol Max Drawdown  Sharpe Total Return
0      -0.0725  0.7572       0.0882  0.1165      -0.0485  3.0858       0.3226
1      -0.0931  0.8721       0.1147  0.1315      -0.0262  3.1571       0.1988
2      -0.0429  1.1331       0.0574  0.0507      -0.0188  2.9939       0.1443
3      -0.0793  0.6055       0.0875  0.1445      -0.0573  3.3587       0.4577
4       -0.043  0.8112       0.0536  0.0661      -0.0264   2.745       0.1595

   ...  Last3 Years          Last5 Years                          YTD          \
   ... Total Return     Vol Max Drawdown  Sharpe     Vol Max Drawdown  Sharpe
0  ...        0.151  0.1196      -0.1615  0.8955  0.1214      -0.0293  0.5788
1  ...       0.1547  0.1485      -0.2522  0.5788  0.1684      -0.0266  1.2542
2  ...       0.0874  0.0484      -0.0568  1.4855  0.0487      -0.0071  5.6708
3  ...       0.1243    0.15      -0.2111   0.439  0.1494      -0.0489  0.0611
4  ...       0.0948  0.0696      -0.1027   0.897  0.0712      -0.0186   0.836

                                           flag
  Total Return     Vol bottom_5pct_half_periods
0       0.0039  0.1273                        0
1       0.0076  0.1187                        0
2       0.0137  0.0497                        0
3       0.0007  0.2106                        0
4       0.0035  0.0793                        0

[5 rows x 67 columns]

In [ ]:
for keys, values in strategy_rankings_dfs.items():
    display(values)

  Total Return (Last5 Years)  \

0                     0.1087
1                     0.0975
2                     0.0724
3                     0.0656
4                     0.0639

                                       strategy_name         2015  \
                                                     Total Return
0  Sp 500 Futures 12% Intraday Edge Growth Tca Us...          0.0
1                            Sp 500 Futures Index Er          0.0
2  Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...          0.0
3           Sp 500 Dynamic Intraday Tca Index Usd Er          0.0
4  Sp 500 Futures 7% Intraday Edge Volatility Tca...          0.0

          2016                                      2017                       \
  Max Drawdown  Sharpe Total Return     Vol Max Drawdown  Sharpe Total Return
0      -0.0725  0.7572       0.0882  0.1165      -0.0485  3.0858       0.3226
1      -0.0931  0.8721       0.1147  0.1315      -0.0262  3.1571       0.1988
2      -0.0429  1.1331       0.0574  0.0507      -0.0188  2.9939       0.1443
3      -0.0793  0.6055       0.0875  0.1445      -0.0573  3.3587       0.4577
4       -0.043  0.8112       0.0536  0.0661      -0.0264   2.745       0.1595

   ...  Last3 Years          Last5 Years                          YTD          \
   ... Total Return     Vol Max Drawdown  Sharpe     Vol Max Drawdown  Sharpe
0  ...        0.151  0.1196      -0.1615  0.8955  0.1214      -0.0293  0.5788
1  ...       0.1547  0.1485      -0.2522  0.5788  0.1684      -0.0266  1.2542
2  ...       0.0874  0.0484      -0.0568  1.4855  0.0487      -0.0071  5.6708
3  ...       0.1243    0.15      -0.2111   0.439  0.1494      -0.0489  0.0611
4  ...       0.0948  0.0696      -0.1027   0.897  0.0712      -0.0186   0.836

                                           flag
  Total Return     Vol bottom_5pct_half_periods
0       0.0039  0.1273                        0
1       0.0076  0.1187                        0
2       0.0137  0.0497                        0
3       0.0007  0.2106                        0
4       0.0035  0.0793                        0

[5 rows x 67 columns]

  Total Return (Last10 Years)  \

0                      0.1354
1                      0.1344
2                      0.1285
3                       0.083
4                      0.0773

                                       strategy_name         2015  \
                                                     Total Return
0           Sp 500 Dynamic Intraday Tca Index Usd Er          0.0
1  Sp 500 Futures 12% Intraday Edge Growth Tca Us...          0.0
2                            Sp 500 Futures Index Er          0.0
3  Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...          0.0
4  Sp 500 Futures 7% Intraday Edge Volatility Tca...          0.0

          2016                                      2017                       \
  Max Drawdown  Sharpe Total Return     Vol Max Drawdown  Sharpe Total Return
0      -0.0793  0.6055       0.0875  0.1445      -0.0573  3.3587       0.4577
1      -0.0725  0.7572       0.0882  0.1165      -0.0485  3.0858       0.3226
2      -0.0931  0.8721       0.1147  0.1315      -0.0262  3.1571       0.1988
3      -0.0429  1.1331       0.0574  0.0507      -0.0188  2.9939       0.1443
4       -0.043  0.8112       0.0536  0.0661      -0.0264   2.745       0.1595

   ... Last3 Years  Last5 Years                                       YTD  \
   ...         Vol Max Drawdown  Sharpe Total Return     Vol Max Drawdown
0  ...        0.15      -0.2111   0.439       0.0656  0.1494      -0.0489
1  ...      0.1196      -0.1615  0.8955       0.1087  0.1214      -0.0293
2  ...      0.1485      -0.2522  0.5788       0.0975  0.1684      -0.0266
3  ...      0.0484      -0.0568  1.4855       0.0724  0.0487      -0.0071
4  ...      0.0696      -0.1027   0.897       0.0639  0.0712      -0.0186

                                                   flag
   Sharpe Total Return     Vol bottom_5pct_half_periods
0  0.0611       0.0007  0.2106                        0
1  0.5788       0.0039  0.1273                        0
2  1.2542       0.0076  0.1187                        0
3  5.6708       0.0137  0.0497                        0
4   0.836       0.0035  0.0793                        0

[5 rows x 67 columns]

  Sharpe (Last5 Years)                                      strategy_name  \

0               1.4855  Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...
1                0.897  Sp 500 Futures 7% Intraday Edge Volatility Tca...
2               0.8955  Sp 500 Futures 12% Intraday Edge Growth Tca Us...
3               0.5788                            Sp 500 Futures Index Er
4                0.439           Sp 500 Dynamic Intraday Tca Index Usd Er

          2015         2016                                      2017          \
  Total Return Max Drawdown  Sharpe Total Return     Vol Max Drawdown  Sharpe
0          0.0      -0.0429  1.1331       0.0574  0.0507      -0.0188  2.9939
1          0.0       -0.043  0.8112       0.0536  0.0661      -0.0264   2.745
2          0.0      -0.0725  0.7572       0.0882  0.1165      -0.0485  3.0858
3          0.0      -0.0931  0.8721       0.1147  0.1315      -0.0262  3.1571
4          0.0      -0.0793  0.6055       0.0875  0.1445      -0.0573  3.3587

                ...  Last3 Years          Last5 Years                       \
  Total Return  ... Total Return     Vol Max Drawdown Total Return     Vol
0       0.1443  ...       0.0874  0.0484      -0.0568       0.0724  0.0487
1       0.1595  ...       0.0948  0.0696      -0.1027       0.0639  0.0712
2       0.3226  ...        0.151  0.1196      -0.1615       0.1087  0.1214
3       0.1988  ...       0.1547  0.1485      -0.2522       0.0975  0.1684
4       0.4577  ...       0.1243    0.15      -0.2111       0.0656  0.1494

           YTD                                                  flag
  Max Drawdown  Sharpe Total Return     Vol bottom_5pct_half_periods
0      -0.0071  5.6708       0.0137  0.0497                        0
1      -0.0186   0.836       0.0035  0.0793                        0
2      -0.0293  0.5788       0.0039  0.1273                        0
3      -0.0266  1.2542       0.0076  0.1187                        0
4      -0.0489  0.0611       0.0007  0.2106                        0

[5 rows x 67 columns]

  Sharpe (Last10 Years)                                      strategy_name  \

0                1.6802  Sp Multi-Asset 5% Intraday Edge Macro Tca Inde...
1                1.1304  Sp 500 Futures 12% Intraday Edge Growth Tca Us...
2                1.1049  Sp 500 Futures 7% Intraday Edge Volatility Tca...
3                0.9152           Sp 500 Dynamic Intraday Tca Index Usd Er
4                0.7196                            Sp 500 Futures Index Er

          2015         2016                                      2017          \
  Total Return Max Drawdown  Sharpe Total Return     Vol Max Drawdown  Sharpe
0          0.0      -0.0429  1.1331       0.0574  0.0507      -0.0188  2.9939
1          0.0      -0.0725  0.7572       0.0882  0.1165      -0.0485  3.0858
2          0.0       -0.043  0.8112       0.0536  0.0661      -0.0264   2.745
3          0.0      -0.0793  0.6055       0.0875  0.1445      -0.0573  3.3587
4          0.0      -0.0931  0.8721       0.1147  0.1315      -0.0262  3.1571

                ... Last3 Years  Last5 Years                               \
  Total Return  ...         Vol Max Drawdown  Sharpe Total Return     Vol
0       0.1443  ...      0.0484      -0.0568  1.4855       0.0724  0.0487
1       0.3226  ...      0.1196      -0.1615  0.8955       0.1087  0.1214
2       0.1595  ...      0.0696      -0.1027   0.897       0.0639  0.0712
3       0.4577  ...        0.15      -0.2111   0.439       0.0656  0.1494
4       0.1988  ...      0.1485      -0.2522  0.5788       0.0975  0.1684

           YTD                                                  flag
  Max Drawdown  Sharpe Total Return     Vol bottom_5pct_half_periods
0      -0.0071  5.6708       0.0137  0.0497                        0
1      -0.0293  0.5788       0.0039  0.1273                        0
2      -0.0186   0.836       0.0035  0.0793                        0
3      -0.0489  0.0611       0.0007  0.2106                        0
4      -0.0266  1.2542       0.0076  0.1187                        0

[5 rows x 67 columns]

In [ ]:
cols = strategy_rankings.columns
cols

MultiIndex([('strategy_name',              ''),
            (         '2015',  'Total Return'),
            (         '2016', ' Max Drawdown'),
            (         '2016',       ' Sharpe'),
            (         '2016',          ' Vol'),
            (         '2016',  'Total Return'),
            (         '2017', ' Max Drawdown'),
            (         '2017',       ' Sharpe'),
            (         '2017',          ' Vol'),
            (         '2017',  'Total Return'),
            (         '2018', ' Max Drawdown'),
            (         '2018',       ' Sharpe'),
            (         '2018',          ' Vol'),
            (         '2018',  'Total Return'),
            (         '2019', ' Max Drawdown'),
            (         '2019',       ' Sharpe'),
            (         '2019',          ' Vol'),
            (         '2019',  'Total Return'),
            (         '2020', ' Max Drawdown'),
            (         '2020',       ' Sharpe'),
            (         '2020',          ' Vol'),
            (         '2020',  'Total Return'),
            (         '2021', ' Max Drawdown'),
            (         '2021',       ' Sharpe'),
            (         '2021',          ' Vol'),
            (         '2021',  'Total Return'),
            (         '2022', ' Max Drawdown'),
            (         '2022',       ' Sharpe'),
            (         '2022',          ' Vol'),
            (         '2022',  'Total Return'),
            (         '2023', ' Max Drawdown'),
            (         '2023',       ' Sharpe'),
            (         '2023',          ' Vol'),
            (         '2023',  'Total Return'),
            (         '2024', ' Max Drawdown'),
            (         '2024',       ' Sharpe'),
            (         '2024',          ' Vol'),
            (         '2024',  'Total Return'),
            (         '2025', ' Max Drawdown'),
            (         '2025',       ' Sharpe'),
            (         '2025',          ' Vol'),
            (         '2025',  'Total Return'),
            (         '2026', ' Max Drawdown'),
            (         '2026',       ' Sharpe'),
            (         '2026',          ' Vol'),
            (         '2026',  'Total Return'),
            (  'Last1 Years', ' Max Drawdown'),
            (  'Last1 Years',       ' Sharpe'),
            (  'Last1 Years',          ' Vol'),
            (  'Last1 Years',  'Total Return'),
            ( 'Last10 Years', ' Max Drawdown'),
            ( 'Last10 Years',       ' Sharpe'),
            ( 'Last10 Years',          ' Vol'),
            ( 'Last10 Years',  'Total Return'),
            (  'Last3 Years', ' Max Drawdown'),
            (  'Last3 Years',       ' Sharpe'),
            (  'Last3 Years',          ' Vol'),
            (  'Last3 Years',  'Total Return'),
            (  'Last5 Years', ' Max Drawdown'),
            (  'Last5 Years',       ' Sharpe'),
            (  'Last5 Years',          ' Vol'),
            (  'Last5 Years',  'Total Return'),
            (          'YTD', ' Max Drawdown'),
            (          'YTD',       ' Sharpe'),
            (          'YTD',          ' Vol'),
            (          'YTD',  'Total Return')],
           names=['Period', 'metric_type'])

### Get the Weights and Returns for Different Rebalancing Rules

In [ ]:
strat_1 = add_weights(merged_returns, r=0.01, spec=2, q_level=7)
strat_2 = add_weights(merged_returns, r=0.01, spec=2, q_level=8)
strat_3 = add_weights(merged_returns, r=0.02, spec=1, q_level=8)

In [ ]:
# Save the Results of the one of the startegies
perf_1 = get_performance_metrics(strat_1)

In [ ]:
# Compare the performance of different strategies over same period (last 10 years)
pd.concat([
    get_performance_metrics(strat_1).tail(1).assign(strategy='spec2_q8'),
    get_performance_metrics(strat_2).tail(1).assign(strategy='spec1_q8'),
    get_performance_metrics(strat_3).tail(1).assign(strategy='spec2_q7')
], ignore_index=True)

### Find the Best Performing Strategy

We begin with a baseline row, which is just the s&p 500 raw performance

In [ ]:
# To comapre the performance of strategies, we will prioritise those metrics over the last 10 years,
# which is the last row of a given performance DataFrame
# to begin with, we need everything but the first 4 columns, which are the start and end dates
# and the total return (non-annualised) for the S&P 500 and the risk control strategy
# and additionally, only the metrics for s&p500 without the risk control strategy, which is every odd
# column starting from the 5th column (index 4). THIS IS TO SERVE AS A BASELINE FOR COMPARISON

# here, we extract a 1 row dataframe with the last row of the performance DataFrame
# but every second column starting from the 5th column (index 4)
# this is to get the S&P 500 performance metrics as a baseline for comparison

baseline_row = perf_1.iloc[-1, 4::2].to_frame().T.reset_index(drop=True)

# convert everything to float
baseline_row = baseline_row.astype(float)

# add the first column as a strategy name, this one is S&P500 (Baseline)
baseline_row.insert(0, 'Strategy', 'S&P500 (Baseline)')

# add a second, third and fourth column with the 
# quantile level, the maximum drawdown and the specification (these should be empty
# since this is the baseline)
baseline_row.insert(1, 'Quantile Level', np.nan)  # q_level
baseline_row.insert(2, 'Maximum Drawdown', np.nan)  # r
baseline_row.insert(3, 'Specification', np.nan)  # spec

#rename the columns to remove the 'S&P500 ' prefix
baseline_row.columns = [col.replace('S&P500 ', '') for col in baseline_row.columns]

# Move annualised sharpe ratio and annulaised returns to  be the first columns
# this is to make it easier to compare the strategies
priority_cols = ['Annualized Sharpe Ratio', 'Annualized Return']
baseline_row = baseline_row[priority_cols + 
                        [col for col in baseline_row.columns if col not in priority_cols]]

# baseline_row

#### Create a Function that Extracts the Relevant (10-year) Performance Metrics

In [ ]:
# Here, we define a function that takes as input a performance DataFrame 
# and returns a DataFrame with the last row and only those metrics corresponding to the strategy
def get_strategy_performance_row(perf_df, strategy_name, q_level=8, r=0.01, spec=2):
    """
    Extract the last row of performance metrics for a specific strategy.

    Args:
        perf_df (pd.DataFrame): DataFrame containing performance metrics.
        strategy_name (str): Name of the strategy to extract.

    Returns:
        pd.DataFrame: DataFrame with the last row of performance metrics for the specified strategy.
    """
    # Get the last row of the performance DataFrame, and select every second column 
    # starting from the 5th column (index 4), since these pertain to the metrics
    # for the S&P 500 with the risk control strategy
    last_row = perf_df.iloc[-1, 5::2].to_frame().T.reset_index(drop=True)
    
    # Convert everything to float
    last_row = last_row.astype(float)
    
    # Add the strategy name as the first column
    last_row.insert(0, 'Strategy', strategy_name)

    # add a second, third and fourth column with the 
    # quantile level, the maximum drawdown and the specification
    last_row.insert(1, 'Quantile Level', q_level)  # q_level
    last_row.insert(2, 'Maximum Drawdown', f'{r*100:.2f}%')  # r
    last_row.insert(3, 'Specification', spec)  # spec
    
    # Rename the columns to remove the 'S&P500 ' prefix
    last_row.columns = [col.replace('S&P500 Risk Control ', '') for col in last_row.columns]
    # Move annualised sharpe ratio and annulaised returns to  be the first columns
    # this is to make it easier to compare the strategies
    priority_cols = ['Annualized Sharpe Ratio', 'Annualized Return']
    last_row = last_row[priority_cols + 
                         [col for col in last_row.columns if col not in priority_cols]]

    
    
    
    return last_row

#### Iteratively Add to a Dataframe to Store Comparative Results

In [ ]:
# define a function that creates a performance comparison DataFrame
def create_performance_comparison_df(r_list, q_level_list, spec_list, base_row = baseline_row, merged_df = merged_returns)   -> pd.DataFrame:
    """
    Create a DataFrame to compare the performance of different strategies.
    Args:
        base_row (pd.DataFrame): The baseline row to start the comparison with.
        r_list (list): list of maximum drawdown values for different strategies.
        q_level_list (list): list of quantile levels for different strategies.
        spec_list (list): list of specifications for different strategies.
    
    Returns:
        pd.DataFrame: DataFrame with the baseline row and space for additional strategies.
    """
    # initialise the dataframe to store the performance metrics for each strategy
    # as simply the baseline row
    performance_comparison_df = base_row.copy()

    # for each combination of r, q_level and spec, get the returns for the strategy
    # using the add_weights function.
    # then, using the output of that get performance metrics for the strategy using the 
    # get_performance_metrics function
    # and then get the last row of the performance DataFrame using the get_strategy_performance_row function
    for r, q_level, spec in zip(r_list, q_level_list, spec_list):
        # Get the quantile level as a percentage
        pct_level = quantile_level_map[q_level]
        # Get the strategy name based on the quantile level, maximum drawdown and specification
        strategy_name = f'{100*pct_level:.1f}% Worst Drawdown <= {r*100:.2f}%'
        
        # Get the strategy DataFrame with target and actual weights
        strategy_df = add_weights(merged_df, r=r, spec=spec, q_level=q_level)
        
        # Get the performance metrics for the strategy
        perf_metrics = get_performance_metrics(strategy_df, save=False)
        
        # Get the last row of performance metrics for the strategy
        last_row = get_strategy_performance_row(perf_metrics, strategy_name, q_level=q_level, r=r, spec=spec)
        
        # Append this row to the performance comparison DataFrame
        performance_comparison_df = pd.concat([performance_comparison_df, last_row], ignore_index=True)

    # Add a placeholder for future strategies
    return performance_comparison_df

In [ ]:
# create a list of r, q_level and spec values to compare
r_list = [0.007, 0.008, 0.01, 0.012]
q_level_list = [7,8]
spec_list = [2]

# get all combinations of r, q_level and spec using itertools.product
r_list, q_level_list, spec_list = zip(*product(r_list, q_level_list, spec_list))
r_list

In [ ]:

#augment these so that we have a list of all combinations of r, q_level and spec
# get the performance comparison DataFrame
performance_comparison_df = create_performance_comparison_df(
    r_list=r_list,
    q_level_list=q_level_list,
    spec_list=spec_list,
    base_row=baseline_row,
    merged_df=merged_returns
)

In [ ]:
# sort in decreasing order of annualized Sharpe ratio, followed by annualized return
performance_comparison_df = performance_comparison_df.sort_values(
    by=['Annualized Sharpe Ratio', 'Annualized Return'],ascending=False)

# Inspect the performance comparison DataFrame
performance_comparison_df

In [ ]:
# extract the parameters of the best strategy based on the annualized Sharpe ratio
# this means q_level, r and spec are the values under the 
# columns 'Quantile Level', 'Maximum Drawdown' and 'Specification' in the top row
best_strategy_params = performance_comparison_df.iloc[0][['Quantile Level', 'Maximum Drawdown', 'Specification']].to_dict()
best_q_level = int(best_strategy_params['Quantile Level'])
best_r = float(best_strategy_params['Maximum Drawdown'].strip('%')) / 100  # convert to float and divide by 100 to get the decimal value
best_spec = int(best_strategy_params['Specification'])

# Get the returns for the best strategy
strat_1 = add_weights(merged_returns, r=best_r, spec=best_spec, q_level=best_q_level)

#display the best parameters
display(best_strategy_params)

# save the performance dataframe corresponding to this to a nice excel
perf_1 = get_performance_metrics(strat_1)
save_with_bold_highlights(perf_1, "../data/strat_1_performance.xlsx")

In [ ]:
# With the best performing strategy, get the total returns for the specified window: first period of interest is covid
merged_returns_1, weights_df_1 = calc_total_returns(strat_1, start_date='2020-01-01', end_date='2020-12-31')

In [ ]:
weights_df_1.head()

In [ ]:
merged_returns_1.head()

## Visualisation

In [ ]:
# Melt the dataframe to long format for plotting
# Use all columns except 'time' as value_vars
plot_df_1 = merged_returns_1.melt(
    id_vars=['time', 'time_label'],
    var_name='return_type',
    value_name='return_value'
)

In [ ]:
plot_df_1.head()

#### Add a Label Mapping for Each Type of Return

In [ ]:
# Get the unique return types from the melted DataFrame
return_types = plot_df_1['return_type'].dropna().unique()

# Create a label mapping that maps the return types to more compact labels
# Initialize an empty dictionary for return type labels
return_type_labels = {}
# Loop through each unique return type
for rt in return_types:
    # If the return type is 'return', label as 'Returns'
    if rt == 'return':
        return_type_labels[rt] = 'S&P500 Daily Returns'
    # If the return type is 'total_return', label as 'Total Return'
    elif rt == 'total_return':
        return_type_labels[rt] = 'S&P500 Total Return'
    # If the return type is 'total_index_return', label as 'Total Index Return'
    elif rt == 'total_risk_control_return':
        return_type_labels[rt] = 'S&P500 Risk Control \n Total Return'
    # If the return type starts with 'q_', replace with 'Q' (e.g., 'q_1' -> 'Q1')
    # and add 'Forecast' suffix
    elif rt.startswith('q_'):
        quantile_num = rt.split('_')[1]
        quantile_level = quantile_level_map.get(int(quantile_num))
        return_type_labels[rt] = f'Q{quantile_num} Forecast ({100*quantile_level:.2f}%)'
        # return_type_labels[rt] = f'Q{quantile_num} Forecast'
    # Otherwise, use the return type as the label
    else:
        return_type_labels[rt] = rt

#### Add a Linetype Mapping for Each Type of Return

In [ ]:
# Map each return type to dashed type by default
linetype_map = {rt: 'solid' for rt in return_types}

# Change linetype in linetype map to solid for any key containing 'return'
for key in linetype_map:
    if 'return' in str(key):
        linetype_map[key] = 'solid'

In [ ]:
linetype_map

In [ ]:
# Create a transparency/alpha mapping
alpha_map = {}
# Loop through each return type and assign an alpha (transparency) value
for i, rt in enumerate(return_types):
    # Lower alpha for 'return' (raw returns)
    if rt == 'return':
        alpha_map[rt] = 0.3
    # Medium alpha for 'total_return' (cumulative returns)
    elif '_return' in str(rt):
        alpha_map[rt] = 0.8
    # Gradually decreasing alpha for quantile series (q_*)
    elif rt.startswith('q_'):
        alpha_map[rt] = 0.9 - 0.05 * i
    # Default alpha for any other types
    else:
        alpha_map[rt] = 0.3

In [ ]:
alpha_map

#### Add a Colour Mapping for Each type of Return

In [ ]:
#### Add a Colour Mapping for Each type of Return
# Create a mapping for colors for each return_type using a yellow to red gradient

# Use matplotlib's colormap to generate a yellow-to-red spectrum
cmap = plt.get_cmap('autumn_r')  # red to yellow
colors = [mcolors.to_hex(cmap(i / (len(return_types) - 1))) for i in range(len(return_types))]

# Map each return_type to a color
color_map = dict(zip(return_types, colors))

# change the color for 'return' to black
color_map['return'] = 'black'

# change the color for 'total_return' to green
color_map['total_return'] = 'lightgreen'

# change the color for total_index_return to dark green
color_map['total_risk_control_return'] = 'green'

In [ ]:
color_map

### X Series Labels

In [ ]:

def gen_x_labels(plot_df, n_ticks=10):
    """
    Generate evenly spaced x-axis breaks and labels for plotting.

    Args:
        plot_df (pd.DataFrame): DataFrame containing 'time' and 'time_label' columns.
        n_ticks (int): Maximum number of ticks/labels to generate.

    Returns:
        tuple: (time_breaks, time_labels)
    """
    # Select only the 'time' and 'time_label' columns, remove duplicates, and sort by time
    label_df = plot_df[['time', 'time_label']].drop_duplicates().sort_values('time')
    # Ensure we do not request more ticks than available unique dates
    n_ticks = min(n_ticks, len(label_df))
    # Calculate step size to evenly space the ticks
    step = max(1, len(label_df) // n_ticks)
    # Select every 'step'-th row to get evenly spaced ticks, up to n_ticks
    label_df_filtered = label_df.iloc[::step, :].head(n_ticks)
    # Extract the list of datetime breaks for the x-axis
    time_breaks = label_df_filtered['time'].tolist()
    # Extract the corresponding string labels for the x-axis
    time_labels = label_df_filtered['time_label'].tolist()
    return time_breaks, time_labels

In [ ]:
# filter out the rows where return_type is 'return'
#plot_df = plot_df[plot_df['return_type'] != 'return']

### Plot the Returns of the Target Weights Strategy During Windows of Interest

In [ ]:
def plot_returns(plot_df, plot_name=None):
    """
    Create a ggplot object for returns and forecast quantiles.

    Args:
        plot_df (pd.DataFrame): DataFrame in long format with columns ['time', 'time_label', 'return_type', 'return_value'].

    Returns:
        plotnine.ggplot.ggplot: The ggplot object (not displayed).
    """
    # Generate x-axis breaks and labels
    time_breaks, time_labels = gen_x_labels(plot_df)

    # Determine plot title based on return_types present
    return_types = plot_df['return_type'].unique()
    has_return = any(rt == 'return' for rt in return_types)
    has_q = any(str(rt).startswith('q_') and str(rt)[2:].isdigit() for rt in return_types)
    if plot_name:
        plot_title = plot_name
    elif has_return and has_q:
        plot_title = "Comparison of Returns and Forecast Quantiles"
    else:
        plot_title = "Comparison of Total Returns"

    # Create the plot using plotnine (ggplot-style)
    plot = (
        # Set up the basic plot with aesthetics: x=time, y=return_value, color/linetype/alpha by return_type
        ggplot(plot_df, aes(x='time', y='return_value', color='return_type', linetype='return_type', alpha='return_type')) +
        # Draw lines for each return_type
        geom_line(size=1) +
        # Manually set linetypes, alpha, and colors for each return_type using the mapping dicts
        scale_linetype_manual(values=linetype_map, labels=return_type_labels) +
        scale_alpha_manual(values=alpha_map) +
        scale_color_manual(values=color_map, labels=return_type_labels) +
        # Set plot and axis labels
        labs(
            title=plot_title,
            x='Time',
            y="Returns (%)",
            color='Variable'
        ) +
        # Set x-axis breaks and labels for dates
        scale_x_date(breaks=time_breaks, labels=time_labels) +
        # Format y-axis as percentage values
        scale_y_continuous(labels=lambda l: [f"{v*100:.3f}%" for v in l]) +
        # Customize theme: rotate x labels, move legend, center title, set figure size
        theme(
            axis_text_x=element_text(rotation=90, ha='center'),
            legend_position='right',
            plot_title=element_text(ha='center'),
            figure_size=(12, 6)
        ) +
        # Remove linetype and alpha guides from legend
        guides(linetype=False, alpha=False)
    )
    return plot

### Plot the Weights Over Time

#### Set Up Long Plotting Dataframes

In [ ]:
# Melt the weights dataframe to long format for plotting
# Use all columns except 'time' as value_vars
weights_plot = weights_df_1.melt(
    id_vars=['time', 'time_label'],
    var_name='weight_type',
    value_name='weight_value'
)

In [ ]:
# add a color mapping for the weights
weights_color_map = {
    'target_weight': 'blue',
    'actual_weight': 'purple'
}

# add a label mapping for the weights
weights_label_map = {
    'target_weight': 'Target Weight',
    'actual_weight': 'Index Weight'
}

# create a transparency/alpha mapping for the weights
weights_alpha_map = {
    'target_weight': 0.4,
    'actual_weight': 0.8
}

In [ ]:
def plot_w(weights_plot_df, plot_name=None):
    """
    Create a ggplot object for target and index weights over time.

    Args:
        weights_plot_df (pd.DataFrame): DataFrame in long format with columns ['time', 'time_label', 'weight_type', 'weight_value'].

    Returns:
        plotnine.ggplot.ggplot: The ggplot object (not displayed).
    """
    # Generate x-axis breaks and labels for clear date ticks
    time_breaks, time_labels = gen_x_labels(weights_plot_df)

    if plot_name:
        plot_title = plot_name
    else:
        plot_title = "Target and Actual Weights in Market Index Over Time"

    # Create the plot using plotnine (ggplot-style)
    plot_w_targ = (
        # Set up the basic plot with aesthetics: x=time, y=weight_value, color/alpha by weight_type
        ggplot(weights_plot_df, aes(x='time', y='weight_value', color='weight_type', alpha='weight_type')) +
        # Draw lines for each weight_type
        geom_line(size=1) +
        # Set plot and axis labels
        labs(
            title=plot_title,
            x='Time',
            y='Weight',
            color='Weight Type'
        ) +
        # Set transparency for each weight_type
        scale_alpha_manual(values=weights_alpha_map) +
        # Set x-axis breaks and labels for dates
        scale_x_date(breaks=time_breaks, labels=time_labels) +
        # Set colors for each weight_type and legend labels
        scale_color_manual(values=weights_color_map, labels=weights_label_map) +
        # Format y-axis to show two decimal places
        scale_y_continuous(labels=lambda l: [f"{v:.2f}" for v in l]) +
        # Customize theme: rotate x labels, center title, set figure size
        theme(
            axis_text_x=element_text(rotation=90, ha='center'),
            plot_title=element_text(ha='center'),
            figure_size=(8, 3)
        ) +
        # Remove unwanted guides from legend (hide alpha legend)
        guides(alpha=False)
    )
    return plot_w_targ

#### During COVID

##### Daily Returns and Forecasted Quantiles with Total Returns

In [ ]:
plot_1 = plot_returns(plot_df_1, plot_name ='S&P500 Raw and Risk-Controlled Returns During the COVID Period')
plot_1

##### Weights

In [ ]:
plot_w_targ = plot_w(weights_plot, plot_name='Target and Actual Weights in Market Index Over the COVID Period')
plot_w_targ

#### During the Whole Window of Data

##### Total Returns

In [ ]:
# now do this for the the whole period of data, but instead, get rid of the day returns and the quantiles
# get the total returns for the whole window, but instead, get rid of the day returns and the quantiles
merged_returns_2, weights_df_2 = calc_total_returns(strat_1)

# Melt the dataframe to long format for plotting
plot_df_2 = merged_returns_2.melt(
    id_vars=['time', 'time_label'],
    value_vars=['total_return', 'total_risk_control_return'],
    var_name='return_type',
    value_name='return_value'
)

# Plot the returns for the whole period
plot_2 = plot_returns(plot_df_2)
plot_2

##### Daily Returns and Forecasted Quantiles

In [ ]:
# just the quantiles and day returns for the whole period

# Melt the dataframe to long format for plotting
plot_df_2b = merged_returns_2.melt(
    id_vars=['time', 'time_label'],
    value_vars=['return'] + [f'q_{i}' for i in [1,4,7,8]], 
    var_name='return_type',
    value_name='return_value'
)

# Plot the returns for the whole period
plot_3 = plot_returns(plot_df_2b, plot_name='S&P500 Forecast Quantiles and Daily Returns for the Whole Period')
plot_3

##### Weights

In [ ]:
# create another melted DataFrame for the weights
weights_plot_2 = weights_df_2.melt(
    id_vars=['time', 'time_label'],
    var_name='weight_type',
    value_name='weight_value'
)

plot_w_targ_2 = plot_w(weights_plot_2)
plot_w_targ_2

#### During the 2021 Rate Hikes

##### Daily Returns and Forecasted Quantiles with Total Returns

In [ ]:
# Get the total returns for the 2021 rate hikes period
# Define the window for the 2021 rate hikes (e.g., 2021-01-01 to 2022-12-31)
merged_returns_3, weights_df_3 = calc_total_returns(strat_1, start_date='2021-12-01', end_date='2022-12-31')

# Drop the return column and any q_i type column
#merged_returns_3 = merged_returns_3.drop(columns=['return'] + [f'q_{i}' for i in [1,4,7,8]])

# Melt the dataframe to long format for plotting
plot_df_3 = merged_returns_3.melt(
    id_vars=['time', 'time_label'],
    var_name='return_type',
    value_name='return_value'
)

# Plot the returns for the pandemic period
plot_3 = plot_returns(plot_df_3, plot_name='S&P500 Raw and Risk-Controlled Returns During the 2021 Rate Hikes')
plot_3

##### Weights

In [ ]:
# create another melted DataFrame for the weights
weights_plot_3 = weights_df_3.melt(
    id_vars=['time', 'time_label'],
    var_name='weight_type',
    value_name='weight_value'
)

plot_w_targ_3 = plot_w(weights_plot_3)
plot_w_targ_3